cores = ("amarelo", "branco", "bronze", "preto")
lista_cores = list(cores)
print(lista_cores)
lista_cores.append("dourado")
print(lista_cores)
tupla_cores = tuple(lista_cores)
print(tupla_cores)
lista_cores = list(tupla_cores)
lista_cores.remove("branco")
print(lista_cores)
tupla_cores = tuple(lista_cores)
print(tupla_cores)